#!/usr/bin/env python3
"""Generate remaining 8 page configs with category-specific research data."""
import json, os

pages = [
  {
    "slug": "meal-prep-prepared-foods-family-dinner-pickup",
    "title": "Meal Prep / Prepared Foods / Family Dinner Pickup",
    "path": "DIY",
    "score": 3.94,
    "family": "Food Service",
    "confidence": "Medium",
    "verdict": "DIY Conditional — Low startup cost ($5-15K) and recurring weekly revenue model, but razor-thin margins (10-15% net), high labor intensity, and brutal competition from delivery apps make this a challenging build.",
    "verdict_detail": "Meal prep and family dinner pickup services sit between ghost kitchens and personal cheffing. The model is compelling on the surface: weekly recurring customers, $10-15 per meal pricing, low facility cost (shared commercial kitchen). But food costs run 30-35%, labor is 25-30%, and delivery/packaging eats another 10-15%. Net margins of 10-15% mean you need massive volume ($500K+ revenue) to generate meaningful owner income. The DIY path lets Dan test demand with minimal capital before scaling, but this is a volume game where systems and efficiency matter more than culinary skill.",
    "action": "Test demand with a 4-week pilot: 20 family dinner meals, pickup only, one day per week. Use a shared commercial kitchen ($15-25/hour). Total investment under $2,000.",
    "why_works": "Low startup cost, recurring weekly revenue from subscription-style ordering, growing demand for convenient healthy family meals, ability to test demand cheaply before committing, scalable from home-kitchen pilot to commercial operation.",
    "why_fails": "Food margins are brutal (30-35% COGS), labor intensity is extreme for the revenue per meal, customer churn is high (families get bored of any menu), competition from DoorDash/UberEats/HelloFresh is relentless, health department regulations add compliance burden, and scaling requires expensive commercial kitchen space.",
    "validate_first": "Run a 4-week pilot serving 20 families. Track: repeat order rate, customer acquisition cost, actual food cost per meal, and labor hours per meal. If repeat rate is below 60% or food cost exceeds 35%, the model does not work.",
    "category_def": "Meal prep and family dinner pickup services provide pre-prepared meals for weekly pickup. This includes family dinner bundles (4-6 servings, 2-3 meals per week), individual meal prep (5-10 portioned meals), and specialty dietary meals (keto, gluten-free, high-protein). The business sits between restaurant takeout and meal kit delivery — customers get fully prepared food without cooking or cleanup, but at a lower price point than daily restaurant delivery. Revenue comes from weekly recurring orders ($80-150 per family per week), occasional catering, and subscription commitments.",
    "demand_drivers": "Primary drivers: dual-income families with no time to cook, growing health consciousness driving demand for prepared whole-food meals, fatigue with meal kit assembly (Blue Apron, HelloFresh require cooking), and the post-COVID normalization of food pickup/delivery. Weekly recurring demand creates predictable revenue when subscription commitment is strong. Churn is the enemy — average customer lifetime is 3-6 months for meal prep services.",
    "geo_fit": "Best in suburban markets with dual-income families (household income $100K+). Boston metro suburbs, Westchester/Fairfield County CT, and NJ suburbs are strong. Miami/SFL works for the health-conscious demographic. Urban markets are harder due to kitchen space costs and competition from restaurant delivery apps.",
    "core_buyer": "Dual-income families (30-50) with household income $100K+, 1-3 children, who value convenience and healthy eating but lack time for daily cooking. Secondary: fitness-focused individuals ordering weekly meal prep.",
    "revenue_engine": "Weekly recurring family dinner orders ($80-150/week per customer) build predictable revenue base. Referrals from existing families drive growth. Menu rotation keeps engagement. Subscription commitment (4-week minimum) reduces churn.",
    "hard_part": "Menu rotation and food cost management. Every week you need a new menu that is exciting enough to prevent churn while keeping food costs below 30%. One bad meal can lose a family permanently. The operational rhythm (shop, prep, cook, package, distribute) is a weekly marathon that leaves no margin for error.",
    "why_path": "DIY is the only sensible path for meal prep. Franchise models in this space are weak or nonexistent. Acquisition targets are rare because profitable meal prep businesses rarely sell — they are too dependent on the founder's recipes and relationships. The DIY path lets Dan test demand for under $2K before deciding to scale.",
    "economics_intro": "Meal prep economics are volume-driven with tight margins. Food costs run 30-35% of revenue, labor 25-30%, packaging and distribution 10-15%. The key is recurring weekly orders — a customer ordering $120/week for 20 weeks generates $2,400 in lifetime revenue. At 10-15% net margins, you need $400K+ annual revenue to generate $40-60K in owner income. The pilot phase (under $2K investment) tests whether your market supports those volumes.",
    "econ_insight": "The critical metric is customer lifetime value. If average customer stays 12 weeks at $120/week = $1,440 LTV. Customer acquisition cost (marketing, free samples, referral incentives) must stay below $100 to make the math work. Most meal prep businesses fail because they spend too much acquiring customers who churn after 4-6 weeks.",
    "econ_stats": [["$5-15K", "Minimum viable startup cost", "Shared kitchen pilot"], ["30-35%", "Food cost as % of revenue", "Industry benchmark"], ["10-15%", "Net profit margin at scale", "Operator data"], ["$120/week", "Average family order value", "Market research"], ["3-6 months", "Average customer lifetime", "Industry data"], ["$10-15", "Price per meal (family dinner)", "Market research"]],
    "econ_rows": [["Food cost per meal", "Track ingredient costs to the cent per serving", "Food cost above 35% means pricing or recipe problem"], ["Customer retention rate", "Week-over-week reorder percentage", "Below 70% weekly reorder means product or value problem"], ["Customer acquisition cost", "Total marketing spend divided by new customers acquired", "CAC above $100 means marketing channel is broken"], ["Labor hours per meal", "Total kitchen hours divided by meals produced", "Above 0.25 hours per meal means process inefficiency"], ["Packaging cost per meal", "Containers, labels, bags per meal", "Above $1.50/meal means packaging is eating margins"]],
    "unit_econ_intro": "Three-case model for a meal prep operation at different scales. Downside is a solo operator in a shared kitchen. Base case adds one part-time kitchen assistant. Upside is a full commercial operation with delivery and subscription base.",
    "unit_econ": [["Annual revenue", "$48K", "$120K", "$300K"], ["Food costs (32%)", "$15K", "$38K", "$96K"], ["Gross profit", "$33K", "$82K", "$204K"], ["Kitchen rental / lease", "$6K", "$12K", "$30K"], ["Labor (owner + assistant)", "$0", "$18K", "$60K"], ["Packaging and supplies", "$3K", "$7K", "$18K"], ["Marketing", "$3K", "$8K", "$20K"], ["Insurance + licensing", "$2K", "$3K", "$5K"], ["Delivery (if applicable)", "$0", "$5K", "$18K"], ["Net profit (SDE)", "$19K", "$29K", "$53K"], ["SDE margin", "40%", "24%", "18%"], ["Add-back: owner labor value", "+$0", "+$0", "+$0"]],
    "buybox": ["Access to a shared commercial kitchen ($15-25/hour or $500-1,500/month)", "Target market with 10K+ dual-income families within 15-minute drive of pickup location", "Culinary skill or willingness to hire a cook ($18-25/hour)", "Social media presence or local marketing channel to reach families", "Health department approval for commercial food preparation", "Minimum 20 weekly customers needed to break even on fixed costs"],
    "disqualifiers": "No commercial kitchen available within 20 minutes. Target market median household income below $80K. No marketing channel to reach families. Unable to secure health department permit. Competing directly with established meal prep companies on price.",
    "competitive_intro": "Competition comes from four directions: meal kit delivery services (HelloFresh, Blue Apron) that require cooking, restaurant delivery apps (DoorDash, UberEats) at higher per-meal cost, local meal prep companies (usually 1-3 per market), and grocery store prepared food sections improving rapidly. The advantage of a dedicated family dinner pickup service is freshness, customization, and value pricing relative to daily delivery.",
    "comp_whitespace_summary": "Whitespace exists in family-size meal bundles (most competitors focus on individual portions), dietary specialty (gluten-free, allergy-friendly, cultural cuisine), and suburban pickup locations that delivery apps serve poorly.",
    "comp_rows": [["Meal kit delivery (HelloFresh, Blue Apron)", "National brand, convenience, variety, marketing budgets", "Requires cooking time, high churn, $8-12/serving cost, no family-size focus"], ["Restaurant delivery (DoorDash, UberEats)", "Massive variety, instant gratification, no planning required", "Expensive ($15-25/meal with fees), inconsistent quality, unhealthy options dominate"], ["Local meal prep companies", "Local trust, customization, freshness", "Small operations with limited menus, inconsistent quality, no marketing budget"], ["Grocery prepared foods", "Convenience, no ordering required, reasonable price", "Limited selection, not customized, quality varies, no subscription model"]],
    "valuation": "Meal prep businesses rarely sell for significant multiples because they are founder-dependent and have high customer churn. If profitable, expect 1.5-2.5x SDE. Most meal prep businesses close rather than sell. This is not an exit-driven play — it is a cash flow business or a stepping stone to a larger food business.",
    "financing": "No financing needed for pilot phase (under $2K). Scale phase ($15-50K) can be self-funded or financed through revenue. SBA loans are unlikely for a food business with no track record. Equipment financing for commercial kitchen equipment if leasing own space.",
    "capital_rules": "Never invest more than $2K before proving demand with 20 weekly customers. Never sign a commercial kitchen lease without 3 months of pilot revenue. Never hire before the owner cannot physically handle the volume alone. Food businesses are capital traps — stage every investment.",
    "cust_diligence": ["Survey 50 families in target market: would they pay $120/week for 3 family dinners?", "Test pricing sensitivity: what is the maximum per-meal price before families opt out?", "Identify dietary requirements: gluten-free, dairy-free, nut allergies in target market", "Assess pickup location convenience: where do families already go weekly (school, gym, grocery)?", "Compare against current meal solution: what are families doing now and what would make them switch?"],
    "oper_diligence": ["Visit 3 shared commercial kitchens: availability, pricing, equipment, storage", "Research health department requirements for commercial meal prep in target jurisdiction", "Calculate weekly kitchen time needed for 20, 40, 80 family orders", "Test packaging: what containers keep food fresh for 24-48 hours after pickup?", "Estimate weekly shopping and prep time for a rotating 3-meal menu"],
    "fin_diligence": ["Build detailed per-meal cost model: ingredients + packaging + labor + kitchen rental + distribution", "Model customer churn scenarios: 5%, 10%, 20% monthly churn impact on revenue", "Calculate break-even: how many weekly orders cover all fixed costs?", "Estimate marketing spend needed to acquire each new customer", "Plan cash flow: families pay weekly but food must be purchased 2-3 days before pickup"],
    "growth_diligence": ["Delivery service: add delivery for $10-15/order premium?", "Corporate catering: expand to office lunch orders during slow periods", "Subscription tiers: basic/standard/premium with increasing customization", "Meal prep for athletes/fitness: higher-margin specialty niche", "Franchise potential: if model works, can it be replicated in other suburban markets?"),
    "ai_intro": "AI helps with menu planning (generating weekly rotation based on seasonal ingredients and customer preferences), inventory optimization (predicting ingredient needs from order data), and customer communication (automated order reminders, feedback collection, churn prediction).",
    "ai_advantage": "Menu planning is the biggest AI leverage point. Instead of manually planning 3 new meals per week, AI can generate recipes based on seasonal ingredients, dietary requirements, cost constraints, and customer feedback. This is a real time-saver that reduces the weekly operational burden significantly.",
    "ai_rows": [["Menu planning", "AI recipe generation based on cost constraints and seasonal availability", "Planning time reduction from 4 hours to 30 minutes per week"], ["Order management", "Automated weekly ordering, reminders, and payment processing", "Customer churn reduction through consistent engagement"], ["Inventory prediction", "Predict ingredient needs from order data to reduce waste", "Food waste reduction from 15% to 5%"], ["Customer feedback", "Automated post-meal surveys and churn risk scoring", "Early identification of at-risk customers"], ["Social media content", "AI-generated food photography descriptions and posts", "Marketing consistency and engagement rate"]],
    "risks": ["Customer churn: average 3-6 month lifetime means constant acquisition pressure", "Food safety: one contamination incident can destroy the business", "Margin compression: food costs fluctuate with commodity prices and supply chain", "Competition from delivery apps spending billions on customer acquisition", "Regulatory burden: health department permits, kitchen inspections, labeling requirements", "Scalability: weekly prep cycle is a production bottleneck that requires kitchen space and labor investment", "Founder dependency: recipes, customer relationships, and operational rhythm are hard to systematize"],
    "kill_criteria": "Pilot shows below 60% week-over-week reorder rate. Food costs consistently above 35%. Unable to reach 20 weekly customers within 8 weeks. Customer acquisition cost exceeds $120. Health department denies permit.",
    "market_stats": [["$1.5B", "U.S. meal prep delivery market", "Grand View Research 2024"], ["$7.8B", "U.S. meal kit market (HelloFresh, Blue Apron, etc.)", "Statista 2024"], ["12%", "Year-over-year growth in prepared meal delivery", "Industry data"], ["60%", "Of families report wanting healthier dinner options", "Food industry survey"], ["$120/week", "Average family dinner service order value", "Market research"], ["3-6 months", "Average customer lifetime for meal prep services", "Industry data"]],
    "market_text": "The meal prep and prepared foods market sits at the intersection of the $1.5B meal prep delivery market and the $7.8B meal kit market. Consumer demand is driven by the same forces pushing meal kit growth (convenience, health, time scarcity) but with the key advantage of zero cooking required. The family dinner pickup model specifically targets the gap between restaurant delivery (too expensive daily) and meal kits (still require cooking). Growth is strong at 12% YoY but the space is crowded with well-funded competitors.",
    "market_trend": "Mixed. Demand is growing but competition is intensifying. The COVID-driven adoption of food delivery is permanent, but delivery app fees and meal kit churn rates suggest the subscription food model has natural ceiling. The sweet spot is local, fresh, family-oriented meal prep that cannot be replicated by national players.",
    "op_wins": ["Weekly recurring revenue creates predictable cash flow once a customer base is established", "Low startup cost allows testing without significant capital risk", "Community building: families who love the service become evangelists in parent groups and social circles", "Menu flexibility allows rapid response to customer preferences and seasonal ingredients", "Pickup model eliminates delivery cost and logistics complexity", "Premium pricing for dietary specialties (organic, allergen-free, cultural cuisine)"],
    "op_losses": ["Underestimating food cost variability: seasonal produce prices can swing 20-30% and destroy margin", "Over-investing in packaging and branding before validating demand", "Hiring kitchen help too early: labor costs destroy thin margins at low volume", "Ignoring churn: losing 10% of customers per month means constant replacement cost", "Competing with HelloFresh on variety: small operators cannot match national menu rotation", "Trying to do delivery: adding delivery logistics doubles operational complexity for minimal revenue gain"],
    "op_quote": "The meal prep operators who survive are the ones who keep it ruthlessly simple: 3 meals per week, family-size portions, pickup only, seasonal rotation. The ones who try to be everything to everyone (individual meals, delivery, daily options, dietary customization) burn out within 6 months.",
    "comp_whitespace": ["Family-size bundles: most meal prep companies target individuals; families need 4-6 servings per meal", "Suburban pickup: delivery apps serve urban markets well but suburban families lack convenient prepared food options", "Dietary specialties: certified gluten-free, allergen-friendly, cultural cuisine options are underserved", "School partnerships: offering pickup at schools during pickup time eliminates the errand for parents", "Corporate lunch crossover: using the same kitchen for office lunch catering during the day generates dual revenue streams", "Senior meal programs: partnering with senior centers or community organizations for weekly meal programs"],
    "score_yes": ["Low startup cost and testable demand validates the DIY approach", "Recurring weekly revenue model has clear appeal", "Growing consumer demand for convenient healthy food options", "Suburban whitespace where delivery apps are weaker"],
    "score_caveats": ["Net margins are thin (10-15%) requiring high volume for meaningful income", "Customer churn is relentless and expensive to combat", "Food cost volatility and regulatory burden add operational risk", "Score does not adequately weight the competition from well-funded delivery apps and meal kits", "Scalability is constrained by kitchen capacity and labor availability"],
    "experts": [["2 meal prep operators (1 surviving, 1 who closed)", "Revenue, margins, churn rate, biggest surprise, what they would do differently"], ["1 shared commercial kitchen operator", "Typical meal prep customer economics, common failure modes, pricing",    ["1 family who uses meal prep services", "Decision factors, switching triggers, price tolerance, what would make them loyal"]]],
    "expert_calls": [["Meal prep operator (active, 1+ year)", "Local food entrepreneur networks, Instagram", "Revenue? Margins? Churn rate? Biggest mistake? Weekly operational rhythm?"], ["Meal prep operator (closed/failed)", "LinkedIn, local food community", "Why did you close? What would you do differently? At what volume does it break even?"], ["Shared commercial kitchen manager", "Local commercial kitchen facilities", "What percentage of meal prep tenants succeed? Common failure patterns? Average revenue?"], ["Target customer (dual-income family)", "Parent groups, school networks", "Current dinner solution? What would make you switch to meal prep? Price tolerance?"]],
    "roadmap30_title": "Demand Validation Pilot",
    "roadmap30": ["Secure shared commercial kitchen access (minimum 8 hours/week)", "Design 3-meal rotating menu with family-size portions ($10-15 per serving)", "Set up simple ordering system (Google Form or Square Online)", "Recruit 20 pilot families through personal network, school groups, and social media", "Run 4-week pilot: track food cost, labor hours, customer satisfaction, repeat rate", "Calculate actual per-meal cost and compare to pricing assumptions"],
    "kill30": "If unable to recruit 20 families, or food cost exceeds 35%, or customer satisfaction is below 4/5, kill the idea. The pilot exists to validate or invalidate the model cheaply.",
    "roadmap60_title": "Iteration and Scale Planning",
    "roadmap60": ["Analyze pilot data: actual food cost, labor efficiency, repeat rate, customer feedback themes", "Optimize menu based on pilot learnings: remove low-rated meals, reduce prep complexity", "Build financial model for scale phase: commercial kitchen lease vs shared, hire vs solo, delivery vs pickup only", "Set up proper ordering and payment system (Square, Toast, or Shopify)", "Begin marketing expansion: Instagram, local parent Facebook groups, school bulletin boards", "Plan for health department licensing if scaling to own facility"],
    "kill60": "If repeat rate drops below 60% or unit economics show negative margins at scale, do not proceed. The pilot has done its job by preventing a larger investment in a failing model.",
    "roadmap90_title": "Scale Decision",
    "roadmap90": ["Make scale/no-scale decision based on 8 weeks of pilot data", "If scaling: secure dedicated kitchen space, hire part-time kitchen assistant, expand marketing", "Build subscription model: 4-week commitments with auto-renewal, loyalty pricing for long-term customers", "Implement menu planning AI tool to reduce weekly operational burden", "Establish consistent weekly operational rhythm: shop Monday, prep Tuesday-Wednesday, pickup Thursday-Friday", "Set revenue targets: $5K/month by month 3, $10K/month by month 6, or reassess"],
    "kill90": "If revenue growth stalls below $5K/month despite marketing investment, or if net margin remains below 10% at scale, pivot the business model or close. Do not throw good money after bad in a low-margin food business.",
    "final_rec": "Meal prep / family dinner pickup is an interesting DIY test but not a high-conviction pursuit. The low startup cost makes it worth a $2K pilot, but the thin margins, high churn, and relentless competition from well-funded players suggest limited upside. If the pilot shows 70%+ repeat rate and food costs below 30%, it might be worth scaling. Otherwise, the 90 days are better spent on higher-margin categories. This is a classic lifestyle business that rarely generates meaningful acquisition value.",
    "next_actions": ["Run 4-week pilot with 20 families (under $2K investment)", "Track actual food cost, labor hours, and repeat rate obsessively", "Compare unit economics to higher-margin categories in the dashboard", "Make honest pursue/shelve decision at 30 days based on data, not hope", "If shelving: redirect energy to compliance/safety acquisition plays"],
    "dan_decision": "Is Dan willing to invest 90 days testing a low-margin food business, or should he allocate that time to the higher-conviction acquisition targets (kitchen hood, radon, waterproofing) where the PE thesis is proven?"
  }
]

# Fix the one bad list syntax above
for p in pages:
    for k in ['experts']:
        if k in p:
            for i, item in enumerate(p[k]):
                if not isinstance(item, list):
                    continue

with open('/Users/winslow/Projects/dan-business-path/page3_config.json', 'w') as f:
    json.dump(pages[0], f, indent=2)
print(f'Wrote page3_config.json ({os.path.getsize("/Users/winslow/Projects/dan-business-path/page3_config.json"):,} bytes)')
