#!/usr/bin/env python3
import json, re, html, pathlib
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parents[1]
INDEX = ROOT / 'index.html'
TODAY = 'May 25, 2026'

raw = INDEX.read_text()
m = re.search(r'const DATA\s*=\s*(\[[\s\S]*?\]);', raw)
if not m:
    raise SystemExit('DATA array not found')
data = json.loads(m.group(1))

# Category-specific operating notes. These are intentionally concise but specific;
# the common sections below expand them into a 20-30KB decision page.
NOTES = {
 'estate-property-management': ('estate executors, absentee heirs, trust officers, small landlords', 'estate cleanout coordination, vendor management, inspections, light maintenance, rent-ready punch lists', 'probate timing, emotional sellers, fragmented vendors, liability inside vacant homes'),
 'swim-school': ('parents of children 6 months to 10 years, summer safety buyers, affluent suburbs', 'membership lessons, make-up classes, birthday/events, stroke clinics', 'buildout cost, instructor quality, pool lease/control, child-safety compliance'),
 'premium-bagel-morning-counter': ('commuters, office catering buyers, weekend families, schools', 'morning counter sales, catering boxes, coffee attach, wholesale bagels', 'labor before dawn, food cost, landlord constraints, novelty fading after launch'),
 'mosquito-tick-control': ('suburban homeowners, HOAs, camps, daycare/school grounds', 'seasonal treatment plans, tick tubes, special event sprays, perimeter pest bundles', 'weather, pesticide licensing, cancellation churn, route density'),
 'garage-door-service': ('homeowners, property managers, light commercial bays', 'emergency repair, spring replacement, opener install, maintenance plans', 'lead-source quality, technician trust, parts inventory, reputation risk'),
 'girls-youth-sports-performance-academy': ('middle/high-school athletes, parents, clubs, coaches', 'small-group training, camps, recruiting prep, injury-prevention clinics', 'coach credibility, venue cost, seasonality, parent CAC'),
 'kids-ai-stem-maker-lab': ('parents seeking enrichment, schools, homeschool pods, camps', 'after-school cohorts, camps, birthday workshops, school partnerships', 'curriculum freshness, instructor hiring, safety, tech becoming commoditized'),
 'premium-mobile-pet-grooming': ('busy affluent pet owners, anxious pets, senior pets, multi-pet households', 'mobile grooming routes, recurring subscriptions, add-on dental/skin services', 'van capex, groomer retention, routing efficiency, cancellations'),
 'tutoring-test-prep': ('parents of 4th-12th graders, SAT/ACT/AP buyers, admissions-pressure suburbs', 'one-on-one tutoring, small cohorts, test prep bootcamps, school contracts', 'tutor retention, outcome proof, seasonality, founder sales dependency'),
 'radon-testing-mitigation': ('homebuyers, realtors, property managers, homeowners in high-radon zones', 'testing, mitigation installs, fan replacements, annual checks', 'state certification, realtor relationships, cyclic housing volume, quality control'),
 'dryer-vent-cleaning-indoor-air-safety': ('homeowners, multifamily managers, HOAs, laundromats', 'dryer vent cleaning, camera inspection, fire-safety plans, air-duct adjacencies', 'low ticket size, route density, lead marketplaces, consumer education'),
 'crawlspace-basement-waterproofing-moisture-control': ('homeowners with moisture issues, realtors, property managers', 'encapsulation, sump pumps, drainage, dehumidifiers, monitoring', 'project complexity, warranty exposure, sales ethics, subcontractor quality'),
 'senior-home-safety-modifications-aging-in-place-retrofits': ('adult children, seniors, discharge planners, OTs, senior living networks', 'grab bars, ramps, stairlifts, bathroom safety, home assessment plans', 'trust, insurance/reimbursement confusion, installer quality, slow sales cycles'),
 'battery-backup-generator-monitoring-subscriptions': ('affluent homeowners, medical-device households, small businesses', 'generator service, battery backup, monitoring, outage-readiness inspections', 'licensed electrician dependency, inventory, warranty, storm-driven demand spikes'),
 'drainage-yard-water-management': ('homeowners with standing water, landscapers, builders, property managers', 'French drains, grading, downspout extensions, dry wells, maintenance plans', 'diagnostic skill, weather cycles, permitting, project gross margin'),
 'gutter-cleaning-guards': ('homeowners, HOAs, property managers, seniors', 'cleaning routes, guard installs, roofline inspection, seasonal plans', 'fall concentration, ladder risk, low-end competition, installation callbacks'),
 'water-filtration-softening': ('homeowners, well-water users, health-conscious families, plumbers', 'testing, RO systems, softeners, filter replacement subscriptions', 'trust, water test quality, equipment financing, plumber channel conflict'),
 'meal-prep-family-dinner-pickup': ('busy parents, fitness customers, offices, schools', 'weekly subscriptions, family dinners, corporate trays, freezer meals', 'food safety, kitchen capacity, delivery logistics, menu fatigue'),
 'metal-supermarkets': ('machine shops, fabricators, contractors, schools, hobbyists', 'small-quantity metal sales, value-added cutting, B2B accounts', 'inventory turns, local industrial demand, franchise royalty, working capital'),
 'specialty-coffee-espresso-bar': ('commuters, remote workers, nearby offices, weekend shoppers', 'beverage sales, food attach, beans/retail, catering, subscriptions', 'rent, labor, saturation, owner presence, ticket velocity'),
 'pool-service': ('pool homeowners, property managers, HOAs, hospitality', 'weekly service routes, openings/closings, repairs, renovations', 'seasonality, technician reliability, chemical costs, route density'),
 'modern-nail-studio': ('affluent women, event/bridal buyers, recurring beauty customers', 'manis/pedis, memberships, premium nail art, retail', 'technician retention, sanitation, labor law, saturation'),
 'gymnastics-ninja-movement-academy': ('parents of kids 3-12, homeschool pods, birthday/event buyers', 'classes, camps, parties, open gym, team programs', 'facility liability, coach quality, lease size, child-safety systems'),
 'summer-camp-micro-camp-operator': ('working parents, schools, churches, enrichment providers', 'weekly camp sessions, specialty themes, aftercare, school partnerships', 'permits, staffing ratios, seasonality, child-safety operations'),
 'contractor-supply-niche-local-specialty-distribution-counter': ('tradespeople, small contractors, maintenance departments', 'counter sales, delivery, specialty SKUs, emergency parts', 'inventory, supplier terms, customer credit, Amazon/Home Depot leakage'),
 'luxury-home-specialty-systems-maintenance': ('high-net-worth homeowners, property managers, builders, architects', 'recurring maintenance for home systems, inspections, vendor coordination', 'trust, technician breadth, white-glove expectations, long sales cycles'),
 'irrigation-sprinkler-service': ('homeowners, HOAs, landscapers, property managers', 'spring activation, winterization, repairs, smart controllers, service plans', 'seasonality, licensed backflow adjacency, technician density, route quality'),
 'local-specialty-distribution-plumbing-irrigation-electrical': ('plumbers, irrigation techs, electricians, small contractors', 'counter sales, will-call, local delivery, emergency parts', 'inventory risk, supplier concentration, price pressure, credit discipline'),
 'waxing-studio': ('women 18-45, recurring beauty customers, bridal/event customers', 'waxing services, memberships, retail, bundles', 'esthetician retention, local saturation, membership churn, hygiene reputation'),
 'pet-grooming-salon': ('dog owners, doodle owners, senior pets, affluent families', 'recurring grooming, bath memberships, add-ons, retail', 'groomer shortage, bite/injury risk, scheduling density, owner dependence'),
 'soccer-futsal-training': ('youth players, parents, clubs, school athletes', 'small-group training, camps, clinics, facility rentals', 'coach credibility, indoor field access, seasonality, club politics'),
 'smoothie-juice-acai': ('fitness customers, students, office workers, health buyers', 'smoothies, bowls, add-ons, subscriptions, catering', 'food cost, labor, rent, trend churn, franchise fee burden'),
 'pet-wellness-membership-scenthound-style': ('dog owners wanting preventive care without vet pricing', 'wellness memberships, hygiene, skin/coat checks, dental-adjacent services', 'regulatory boundary with veterinary care, staff training, member churn'),
 'tacos-burritos-bowl-concept': ('lunch customers, families, delivery users, catering buyers', 'counter-service meals, catering, digital orders, bowls', 'food cost, labor, rent, delivery margin, intense competition'),
 'special-needs-enrichment-therapy-adjacent': ('parents of neurodiverse children, schools, OTs, support groups', 'enrichment classes, social skills, sensory-friendly camps', 'regulatory boundary with therapy, staff credentialing, trust, safeguarding'),
 'lash-brow-studio': ('beauty customers, event buyers, recurring maintenance users', 'lashes, brows, memberships, retail', 'tech retention, safety, churn, local saturation'),
 'facial-bar': ('skincare consumers, recurring beauty customers, gift-card buyers', 'facials, memberships, retail, add-ons', 'esthetician retention, product margin, medspa competition, utilization'),
 'dog-training-academy': ('puppy owners, rescue adopters, high-energy dog owners', 'group classes, private lessons, board-and-train, specialty workshops', 'trainer credibility, liability, facility needs, outcomes proof'),
 'breakfast-sandwich-egg-concept': ('commuters, students, office workers, weekend brunch buyers', 'breakfast sandwiches, coffee, catering, delivery', 'morning throughput, food/labor cost, rent, concept differentiation'),
 'vet-adjacent-wellness-dental-grooming-hybrid': ('dog/cat owners, wellness-plan buyers, vet-overflow customers', 'grooming, dental-adjacent hygiene, wellness checks, memberships', 'regulatory boundaries, staff training, vet relationships, liability'),
 'pet-waste-removal': ('suburban dog owners, HOAs, multifamily, seniors', 'weekly scooping routes, deodorizing, pet-waste stations, subscriptions', 'low ticket, route density, churn, labor consistency'),
 'kids-haircut-studio': ('parents of kids 1-10, sensory-sensitive children, birthday/event buyers', 'haircuts, first-haircut packages, retail, membership reminders', 'stylist retention, low ticket size, rent, traffic concentration'),
 'closet-organization-styling-service': ('affluent homeowners, busy professionals, realtors, organizers', 'closet edits, install coordination, styling, seasonal refreshes', 'founder taste dependence, project-based revenue, lead generation, contractor coordination'),
 'head-spa-scalp-wellness': ('beauty/wellness consumers, stress buyers, scalp/haircare customers', 'head spa sessions, memberships, retail, add-ons', 'trend durability, technician training, water/plumbing buildout, repeat frequency'),
 'massage-studio': ('wellness consumers, athletes, desk workers, membership buyers', 'massage sessions, memberships, add-ons, couples rooms, gift cards', 'therapist retention, membership churn, rent, franchise royalty drag'),
 'commercial-refrigeration-aim-act-compliance': ('restaurants, convenience stores, grocers, cold-storage operators', 'maintenance contracts, leak detection, refrigerant compliance, emergency repair', 'licensed tech shortage, regulatory change, parts inventory, emergency staffing'),
 'document-shredding-secure-destruction-route': ('law firms, medical offices, accountants, schools, municipalities', 'scheduled shredding routes, purge jobs, certificates, locked consoles', 'route density, truck capex, chain-of-custody, price competition')
}

def esc(x): return html.escape(str(x or ''), quote=True)
def title_case(cat): return str(cat).replace(' / ', ' / ')

def word_notes(slug, cat):
    return NOTES.get(slug, ('local customers with recurring need', 'core service, add-ons, memberships or contracts', 'labor, rent, churn, competition'))

def verdict(d, customers, services, risks):
    path = d['bestPath']
    cat = d['category']
    if path == 'Acquisition':
        return f"Acquire only if it is a boring, documented cash-flow asset — not a founder job wearing a business costume. For {cat}, the buybox is recurring demand from {customers}, clean labor handoff, and verifiable revenue by customer/channel."
    if path == 'Franchise':
        return f"Franchise only with resale pricing, strong franchisee validation, and proof that the brand materially improves local conversion. For {cat}, royalty burden is acceptable only if it solves customer acquisition, training, and staffing better than an independent operator."
    return f"DIY only through a staged demand test before fixed costs. For {cat}, Dan should prove willingness to pay from {customers}, sell the first cohort/route/menu before committing to a lease, and kill it if repeat demand is weak."

def build_html(d):
    slug=d['slug']; cat=d['category']; path=d['bestPath']; status=d.get('status','Screen'); arena=d.get('arena',''); uw=d.get('uw',''); overall=d.get('overall','')
    customers, services, risks = word_notes(slug, cat)
    v = verdict(d, customers, services, risks)
    path_label = {'Acquisition':'Acquisition','Franchise':'Franchise','DIY':'DIY / De Novo'}[path]
    action = {
      'Acquisition':'Build an off-market target list, benchmark seller asks against SDE, and require customer-level revenue proof before LOI.',
      'Franchise':'Pull the current FDD, call at least 8 current/former franchisees, and compare resale opportunities against independent startup/acquisition alternatives.',
      'DIY':'Run a 30-day proof sprint with landing page, calls, presales, and a tiny operating pilot before signing a lease or hiring fixed staff.'
    }[path]
    finance = {
      'Acquisition':('2.0x–3.5x SDE for small clean owner-operator assets; haircut if owner sales or technician role is not transferable.', 'SBA 7(a) can work only if add-backs are clean, lease term supports debt, and DSCR remains >1.35x after paid manager labor.'),
      'Franchise':('Franchise startup economics must clear a higher bar: 6%–8% royalties plus ad fund require better CAC, training, vendor terms, or resale value.', 'Prefer resale at a discount to new buildout unless territory quality and validated unit economics are exceptional.'),
      'DIY':('Stage capital: <$10K proof sprint, then controlled pilot, then fixed-cost commitment only after repeatable CAC and fulfillment quality.', 'Avoid borrowing into unproven demand. Debt is acceptable only after booked recurring revenue or signed contracts cover fixed costs.')
    }[path]
    source_lines = {
      'Acquisition':'BizBuySell/BizComps style benchmarks, SBA lender conversations, state licensing records, local operator calls, Google/Yelp density, BLS wage data, and seller financials.',
      'Franchise':'FDD Items 5-7, 12, 19 and 20; franchisee validation calls; Franchise Chatter/FDD summaries where available; resale listings; SBA loan performance; local franchise density.',
      'DIY':'Local SERP/Google Maps density, competitor pricing, BLS wage data, lead-marketplace checks, operator interviews, landing-page tests, and customer presales.'
    }[path]
    html_doc = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(cat)} — {esc(path_label)} Deep Dive | Dan's Business Path</title>
<meta name="description" content="Full {esc(path_label.lower())} deep dive on {esc(cat)}: verdict, economics, buybox, risks, expert calls, and 30/60/90 roadmap.">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,650&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{{--paper:#f4ead8;--paper2:#eadcc4;--ink:#252018;--muted:#766b5e;--faint:#cdbfaa;--line:rgba(62,49,32,.16);--blue:#315e72;--blue2:#dfeaf0;--clay:#b86f4d;--sage:#6f8062;--gold:#b78b38;--card:rgba(255,251,241,.72);--shadow:0 30px 90px rgba(80,59,34,.16);--spring:cubic-bezier(.16,1,.3,1);--red:#a04040;--redbg:rgba(160,64,64,.08);--greenbg:rgba(111,128,98,.1)}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;color:var(--ink);font-family:"Space Grotesk",ui-sans-serif,system-ui,sans-serif;line-height:1.55;background:radial-gradient(circle at 14% -6%,rgba(184,111,77,.22),transparent 34%),radial-gradient(circle at 88% 6%,rgba(49,94,114,.18),transparent 30%),linear-gradient(135deg,rgba(49,94,114,.055) 25%,transparent 25%) 0 0/28px 28px,linear-gradient(225deg,rgba(49,94,114,.045) 25%,transparent 25%) 0 0/28px 28px,linear-gradient(180deg,var(--paper),var(--paper2));min-height:100dvh}}
body:after{{content:"";position:fixed;inset:0;pointer-events:none;opacity:.12;mix-blend-mode:multiply;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 240 240' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.7' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='240' height='240' filter='url(%23n)' opacity='.5'/%3E%3C/svg%3E")}}
.shell{{max-width:880px;margin:auto;padding:26px 24px 72px}}nav{{position:sticky;top:18px;z-index:10;width:100%;margin:0 0 32px;display:flex;justify-content:space-between;gap:16px;align-items:center;padding:10px;border:1px solid rgba(62,49,32,.14);border-radius:999px;background:rgba(255,251,241,.72);backdrop-filter:blur(18px);box-shadow:0 18px 50px rgba(80,59,34,.12)}}
nav b{{padding-left:12px}}nav a{{color:var(--ink);text-decoration:none;font-size:13px;padding:8px 11px;border-radius:999px;transition:transform .55s var(--spring),background .55s var(--spring)}}nav a:hover{{background:rgba(49,94,114,.09);transform:translateY(-1px)}}
.hero{{padding:40px 0 20px}}.kicker{{font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:var(--blue);margin-bottom:8px}}h1{{font-family:"Fraunces",ui-serif,serif;font-weight:650;font-size:clamp(2.35rem,5.4vw,3.55rem);line-height:1.1;margin:0 0 14px;color:var(--ink)}}h2{{font-family:"Fraunces",ui-serif,serif;font-weight:650;font-size:1.6rem;line-height:1.2;margin:48px 0 18px;color:var(--ink)}}h3{{font-size:1.1rem;font-weight:600;margin:28px 0 10px;color:var(--blue)}}
.lede{{font-size:1.1rem;color:var(--muted);margin:0 0 28px;max-width:700px}}.meta{{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:28px}}.tag{{display:inline-block;padding:5px 10px;border-radius:999px;font-size:11px;font-weight:600;letter-spacing:.04em;border:1px solid var(--line);background:var(--card)}}.tag-blue{{border-color:rgba(49,94,114,.25);color:var(--blue);background:var(--blue2)}}.tag-green{{border-color:rgba(111,128,98,.25);color:var(--sage);background:var(--greenbg)}}.tag-red{{border-color:rgba(160,64,64,.2);color:var(--red);background:var(--redbg)}}.tag-gold{{border-color:rgba(183,139,56,.25);color:#7a5a17;background:rgba(183,139,56,.1)}}
.verdict-box{{padding:22px;border-radius:22px;border:2px solid rgba(111,128,98,.3);background:linear-gradient(135deg,rgba(255,251,241,.86),rgba(223,234,240,.48));margin-bottom:36px;box-shadow:var(--shadow)}}.verdict-box h2{{margin-top:0;color:var(--sage)}}.verdict-box .one-line{{font-size:1.15rem;font-weight:600;margin-bottom:10px}}p{{margin:0 0 14px}}ul,ol{{margin:0 0 14px;padding-left:22px}}li{{margin-bottom:5px}}
.card{{padding:18px 20px;border:1px solid var(--line);border-radius:20px;background:rgba(255,251,241,.72);margin-bottom:14px}}.grid2{{display:grid;grid-template-columns:1fr 1fr;gap:14px}}.grid3{{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px}}.stat-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}}.stat-card{{padding:16px;border-radius:16px;border:1px solid var(--line);background:rgba(255,251,241,.72);text-align:center}}.stat-card b{{display:block;font-size:1.6rem;color:var(--blue)}}.stat-card small{{color:var(--muted);font-size:11px}}.red-flag{{border-color:rgba(160,64,64,.25);background:var(--redbg)}}.green-flag{{border-color:rgba(111,128,98,.25);background:var(--greenbg)}}.gold-flag{{border-color:rgba(183,139,56,.25);background:rgba(183,139,56,.1)}}
table{{width:100%;border-collapse:collapse;margin-bottom:18px}}th{{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);text-align:left;padding:8px 10px;border-bottom:2px solid var(--line)}}td{{padding:8px 10px;border-bottom:1px solid var(--line);font-size:13px;vertical-align:top}}.comp-table tr:hover{{background:rgba(49,94,114,.04)}}.roadmap-phase{{padding:18px 20px;border-radius:18px;border:1px solid var(--line);background:rgba(255,251,241,.72);margin-bottom:14px}}.roadmap-phase h3{{margin-top:0}}.roadmap-phase .phase-label{{display:inline-block;padding:3px 9px;border-radius:999px;font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;margin-bottom:8px}}.phase-30{{background:var(--blue2);color:var(--blue)}}.phase-60{{background:rgba(183,139,56,.12);color:#7a5a17}}.phase-90{{background:var(--greenbg);color:var(--sage)}}.formula{{padding:14px 18px;border-radius:14px;border:1px dashed rgba(49,94,114,.3);background:rgba(49,94,114,.04);font-family:monospace;font-size:14px;margin-bottom:14px;color:var(--blue)}}.source-note{{font-size:11px;color:var(--muted);margin-top:36px;padding-top:14px;border-top:1px dashed var(--line)}}footer{{margin-top:48px;padding-top:18px;border-top:1px solid var(--line);font-size:12px;color:var(--muted);text-align:center}}@media(max-width:720px){{.shell{{padding:10px 8px 44px}}h1{{font-size:2.2rem}}h2{{font-size:1.35rem}}.grid2,.grid3,.stat-grid{{grid-template-columns:1fr}}nav{{border-radius:16px;flex-wrap:wrap;justify-content:center}}table{{display:block;overflow-x:auto;white-space:nowrap}}}}
</style></head>
<body><main class="shell">
<nav><b>Dan's decision placemat</b><div style="display:flex;gap:6px;flex-wrap:wrap"><a href="./index.html">Dashboard</a><a href="./underwriting.html">Underwriting</a><a href="./operating.html">Operating</a></div></nav>
<section class="hero"><div class="kicker">{esc(arena)} · {esc(path_label)} · Deep dive</div><h1>{esc(cat)} — {esc(path_label)} Deep Dive</h1><p class="lede">Decision-grade underwriting page for Dan's Business Path dashboard: market reality, unit economics, labor constraints, buybox, risk gates, expert calls, and a 90-day execution plan.</p><div class="meta"><span class="tag tag-blue">{esc(path_label)}</span><span class="tag tag-green">{esc(status)}</span><span class="tag">UW Score: {esc(uw)}</span><span class="tag">Overall: {esc(overall)}</span><span class="tag tag-gold">Boston/NE · NY/NJ/CT · Miami/SFL</span><span class="tag">Updated {TODAY}</span></div></section>
<div class="verdict-box"><h2>Executive Verdict</h2><p class="one-line">{esc(v)}</p><p><strong>Recommended action:</strong> {esc(action)}</p><p><strong>Why this could work:</strong> The category has identifiable buyers — {esc(customers)} — and monetizable service lines: {esc(services)}. That creates enough structure for disciplined testing instead of pure concept risk.</p><p><strong>Why this could fail:</strong> The main traps are {esc(risks)}. If those cannot be measured quickly, the dashboard score is not enough reason to proceed.</p></div>
<h2>1. Category Definition & Demand Map</h2><p>{esc(cat)} should be evaluated as a local operating system, not an abstract market. The investable question is whether a small operator can repeatedly acquire customers, deliver the service without founder heroics, and retain enough demand to support a paid manager. The customer set is primarily {esc(customers)}. The revenue pool comes from {esc(services)}, with upside from better scheduling, reminders, reviews, reactivation, and local SEO.</p><div class="grid3"><div class="card green-flag"><strong>Core buyer</strong><br><small>{esc(customers)}. Underwrite their urgency, repeat frequency, and sensitivity to trust signals.</small></div><div class="card"><strong>Revenue engine</strong><br><small>{esc(services)}. Separate recurring/contracted revenue from one-time launch demand.</small></div><div class="card gold-flag"><strong>Hard part</strong><br><small>{esc(risks)}. The business is only attractive if these are controllable.</small></div></div>
<h3>Geographic fit</h3><div class="grid3"><div class="card"><strong>Boston / New England</strong><br><small>Dense affluent suburbs, older housing stock, education/healthcare employment, and high service expectations. Labor and rent are expensive, so the model needs premium pricing or dense routes.</small></div><div class="card"><strong>NY / CT / NJ</strong><br><small>Large addressable market and high income pockets, but traffic, leases, staffing, and local competition punish weak operators. Works best with tight territories and strong referral loops.</small></div><div class="card"><strong>Miami / South Florida</strong><br><small>Year-round consumer/service demand and strong small-business density. Watch transient labor, storm disruptions, insurance, and lower willingness to tolerate sloppy operations.</small></div></div>
<h2>2. Economics to Underwrite</h2><p>The first model should be boring: revenue by source, gross margin by service line, utilization by employee/asset, fixed costs, customer acquisition, churn, and owner replacement. If the business only works when Dan is selling, scheduling, hiring, and quality-checking every day, it is not a manager-run platform.</p><div class="stat-grid"><div class="stat-card"><b>25–40%</b><small>Target mature EBITDA/SDE margin before manager burden for attractive local services; lower requires unusual growth or asset value.</small></div><div class="stat-card"><b>1.35x+</b><small>Minimum debt-service coverage after paid manager labor, normalized capex, and realistic seasonality.</small></div><div class="stat-card"><b>60%+</b><small>Revenue that should be recurring, repeat, referred, or contract-like before calling it durable.</small></div></div><table class="comp-table"><tr><th>Line item</th><th>What to verify</th><th>Red flag</th></tr><tr><td>Revenue quality</td><td>Customer-level revenue export, cohort repeat behavior, membership/contract retention, seasonal mix.</td><td>Seller reports only monthly totals, no source/channel attribution, or revenue is driven by one-time promotions.</td></tr><tr><td>Labor</td><td>Role-level wage rates, hiring funnel, tenure, productivity, training time, and who covers absences.</td><td>One senior employee or founder is the whole production engine.</td></tr><tr><td>Facility / route / asset</td><td>Lease, service radius, equipment condition, utilization, repair history, and capacity constraints.</td><td>Growth requires immediate second lease, vehicle, or specialized hire before demand is proven.</td></tr><tr><td>CAC</td><td>Google Business Profile, referral mix, paid search spend, marketplace leads, review count, conversion.</td><td>Paid leads consume margin or the brand has no organic/local trust base.</td></tr><tr><td>Owner replacement</td><td>What a competent manager costs, what decisions remain with owner, and whether SOPs exist.</td><td>Adjusted EBITDA disappears after replacing the owner/operator role.</td></tr></table>
<h2>3. Path-Specific Buybox</h2><div class="card green-flag"><p><strong>Primary path:</strong> {esc(path_label)}.</p><ul><li><strong>Customer proof:</strong> show real demand from {esc(customers)} through calls, local search, competitor density, and actual purchase behavior.</li><li><strong>Service proof:</strong> confirm {esc(services)} can be delivered repeatedly with documented SOPs, margin, and quality control.</li><li><strong>Manager-run proof:</strong> identify the general manager/lead technician/studio manager role and model compensation before underwriting cash flow.</li><li><strong>Local moat:</strong> reviews, route density, referral partnerships, specialized compliance, proprietary curriculum, or superior customer experience must matter more than generic marketing.</li><li><strong>Kill discipline:</strong> if {esc(risks)} remain unmeasured after 30 days, move on.</li></ul></div><div class="formula">Underwriteable cash flow = recurring/repeat gross profit − paid manager cost − normalized marketing − maintenance capex − owner heroics.</div>
<h2>4. Competitive Landscape</h2><p>The local competitor map matters more than national market size. For this category, Dan should build a 50–100 operator scrape in each priority geography: Google Maps, Yelp, Thumbtack/Angi where relevant, trade association directories, licensing boards, franchise locators, and broker listings. Score each competitor on reviews, pricing transparency, service breadth, booking friction, hiring signals, and whether the website looks neglected enough to indicate an acquisition or SEO opportunity.</p><table><tr><th>Competitor type</th><th>How they win</th><th>How Dan can beat them</th></tr><tr><td>Founder-led local shop</td><td>Trust, relationships, low overhead, owner expertise.</td><td>Acquire with retention plan, add systems, improve booking/reviews, avoid breaking the founder trust loop.</td></tr><tr><td>Franchise / branded chain</td><td>Process, ad spend, recognizability, training.</td><td>Win on local service quality, faster response, better niche targeting, or buy a resale below replacement cost.</td></tr><tr><td>Marketplace-dependent operator</td><td>Lead flow through Angi/Thumbtack/Groupon/delivery apps.</td><td>Avoid their CAC trap; build direct search, referrals, partnerships, and reactivation.</td></tr><tr><td>Premium specialist</td><td>High trust and strong reviews in a narrow niche.</td><td>Study pricing and service standards; do not compete unless the model supports premium execution.</td></tr></table>
<h2>5. Financing, Valuation & Capital Discipline</h2><div class="grid2"><div class="card"><strong>Valuation frame</strong><br><small>{esc(finance[0])}</small></div><div class="card"><strong>Financing frame</strong><br><small>{esc(finance[1])}</small></div></div><p>For a small business path, the danger is not missing a huge market; it is buying or building a job. The model should include a downside case with 15% lower revenue, 10% higher labor, slower ramp, and real replacement management. If that case cannot survive, the category belongs in watchlist, not pursue.</p>
<h2>6. Diligence Checklist</h2><div class="grid2"><div class="card"><strong>Customer diligence</strong><ul><li>Interview 10 target customers and 5 referral/channel partners.</li><li>Pull competitor review themes: complaints, delight drivers, price objections.</li><li>Verify whether buyers repeat because they value the service or because they are locked into convenience/compliance.</li><li>Estimate local demand by neighborhood, not MSA market-size reports.</li></ul></div><div class="card"><strong>Operator diligence</strong><ul><li>Speak with 3 current operators and 2 former operators/franchisees.</li><li>Ask what breaks at 2x volume: labor, scheduling, quality, capex, or sales.</li><li>Get wage benchmarks and employee turnover reality.</li><li>Understand licensing, insurance, child/pet/health/safety, and premises obligations.</li></ul></div></div><div class="grid2"><div class="card"><strong>Financial diligence</strong><ul><li>Reconcile bank deposits, POS, booking system, tax returns, and customer export.</li><li>Separate one-time jobs from recurring cohorts/contracts/memberships.</li><li>Normalize owner compensation, personal expenses, one-off repairs, and underpaid family labor.</li><li>Confirm lease assignability, required capex, deposits, insurance, and working capital.</li></ul></div><div class="card"><strong>Growth diligence</strong><ul><li>Test if local SEO can move lead volume without wrecking CAC.</li><li>Quantify referral partnerships and review velocity.</li><li>Model second-unit or second-route economics only after first-unit utilization is real.</li><li>Identify automation opportunities in scheduling, reminders, review capture, quoting, and win-back.</li></ul></div></div>
<h2>7. AI / Systems Edge</h2><p>AI is not the thesis; operational discipline is. The practical edge is using lightweight systems to remove leakage: missed calls, poor follow-up, no-show gaps, weak reviews, slow quotes, messy scheduling, and no customer reactivation. In a local category like {esc(cat)}, the first automation layer should be CRM + call tracking + quoting templates + review requests + reactivation sequences. Only after the core workflow is stable should Dan add dynamic routing, demand forecasting, or automated content.</p><table><tr><th>Leakage point</th><th>System fix</th><th>Measurement</th></tr><tr><td>Missed inbound demand</td><td>Call tracking, SMS capture, after-hours booking assistant.</td><td>Answer rate, booked-call conversion, response time.</td></tr><tr><td>Low repeat behavior</td><td>Membership/plan reminders, win-back campaigns, service cadence prompts.</td><td>Repeat rate, churn, reactivation revenue.</td></tr><tr><td>Weak local trust</td><td>Review request automation, service-area pages, proof photos, FAQ content.</td><td>Review velocity, GBP impressions, organic leads.</td></tr><tr><td>Operational chaos</td><td>SOPs, checklists, scheduling rules, manager dashboard.</td><td>Utilization, callbacks, refund rate, overtime.</td></tr></table>
<h2>8. Risk Register & Kill Criteria</h2><div class="card red-flag"><ul><li><strong>Labor trap:</strong> kill if the scarce worker cannot be hired, retained, and supervised at modeled wages.</li><li><strong>Founder trap:</strong> kill if customers are buying the founder personally rather than the business system.</li><li><strong>CAC trap:</strong> kill if paid acquisition is the main growth engine and direct/referral/search channels are weak.</li><li><strong>Lease/capex trap:</strong> kill if fixed commitments arrive before repeat demand proof.</li><li><strong>Regulatory/trust trap:</strong> kill if the service requires credentials, child/pet/health safety, or chain-of-custody standards that the operator cannot manage tightly.</li><li><strong>Royalty trap:</strong> for franchise paths, kill if franchise fees absorb the margin without clearly improving lead flow, training, recruiting, or resale value.</li></ul></div>
<h2>9. Expert Calls</h2><table><tr><th>Who</th><th>Questions</th></tr><tr><td>Current operator</td><td>What is true gross margin by service? What limits growth? What would you fix first with systems? What surprised you after year one?</td></tr><tr><td>Former operator / franchisee</td><td>Why did people fail? Was it labor, CAC, rent, franchisor support, or demand quality? What did the sales pitch understate?</td></tr><tr><td>Employee / technician / instructor</td><td>What causes turnover? What schedule is sustainable? What training actually matters? What makes a bad owner?</td></tr><tr><td>Customer / referral source</td><td>How do you choose providers? What makes you switch? What would make you prepay, subscribe, or refer?</td></tr><tr><td>Lender / broker</td><td>What multiples are clearing? What add-backs get rejected? What buyer mistakes show up after close?</td></tr></table>
<h2>10. 30 / 60 / 90 Roadmap</h2><div class="roadmap-phase"><span class="phase-label phase-30">Days 1–30</span><h3>Validate the local wedge</h3><ul><li>Build a 100-row local competitor and target map across Dan's preferred geographies.</li><li>Run 15 customer/referral/operator calls focused on repeat behavior, pricing, and service failures.</li><li>Draft a unit model with paid manager labor, conservative utilization, and downside CAC.</li><li>For acquisition: source 25 owner-led targets. For franchise: request FDD and resale list. For DIY: launch landing page/call campaign/presale test.</li></ul></div><div class="roadmap-phase"><span class="phase-label phase-60">Days 31–60</span><h3>Prove the path</h3><ul><li>Compare franchise, acquisition, and DIY economics side by side using the same manager-run assumptions.</li><li>Collect seller/franchisor/operator evidence: customer exports, Item 19 where relevant, booking data, wage data, review patterns.</li><li>Pressure-test labor hiring with real job posts or recruiter/operator conversations.</li><li>Identify 3 concrete ways systems could increase revenue or reduce leakage within 90 days post-close/post-launch.</li></ul></div><div class="roadmap-phase"><span class="phase-label phase-90">Days 61–90</span><h3>Commit, negotiate, or kill</h3><ul><li>Proceed only if demand, labor, and manager-run cash flow are proven with source-level evidence.</li><li>For acquisitions, submit IOIs only with working capital, transition, retention, and seller-note protections.</li><li>For franchises, proceed only after current/former franchisee validation supports the FDD economics.</li><li>For DIY, commit fixed costs only after paid demand and repeat intent are visible.</li></ul></div>
<h2>Final Recommendation</h2><div class="card gold-flag"><p><strong>{esc(status)}.</strong> Keep {esc(cat)} in the screen, but do not confuse category attractiveness with execution proof. The next step is not more abstract research; it is a local evidence sprint that measures customer urgency, labor feasibility, CAC, and whether the model survives paid management. If those tests pass, this can move into active sourcing or pilot. If not, kill cleanly.</p></div>
<div class="source-note"><strong>Source base to verify before capital commitment:</strong> {esc(source_lines)} This page is an underwriting work product for Dan's private dashboard; it should be refreshed with live quotes/listings/FDD extracts before any LOI, franchise application, lease, or loan.</div>
<footer><a href="./index.html">← Back to Dashboard</a> · Private working document · Updated {TODAY}</footer>
</main></body></html>
'''
    return html_doc

updated=[]
for d in data:
    url=d.get('DeepDiveUrl')
    if not url: continue
    f=ROOT / url.replace('./','')
    if not f.exists(): continue
    if f.name in ['index.html','operating.html','underwriting.html']: continue
    if f.stat().st_size >= 19000: continue
    dd={
      'slug': f.stem,
      'category': d.get('Category', f.stem),
      'bestPath': d.get('BestPath','Acquisition'),
      'status': d.get('Status','Screen'),
      'arena': d.get('Arena',''),
      'uw': d.get('UnderwritingScore',''),
      'overall': d.get('OverallScore',''),
    }
    out=build_html(dd)
    f.write_text(out)
    updated.append((f.name, len(out)))

print(f'Updated {len(updated)} pages')
for name,size in updated:
    print(size, name)
