#!/usr/bin/env python3
from pathlib import Path
import re, html
BASE=Path('/Users/winslow/Projects/dan-business-path')
OBS=Path('/Users/winslow/Documents/Business-Research/Business Transition Engine/Business Path Deep Dives')
OBS.mkdir(parents=True, exist_ok=True)
boiler=(BASE/'drive-thru-coffee-kiosk.html').read_text()
start=boiler[:boiler.index('<section class="hero">')]
end='</main>\n</body>\n</html>'

SBA='SBA 7(a): eligible for changes of ownership up to $5M; source: https://www.sba.gov/funding-programs/loans/7a-loans'
items=[
{
'slug':'distressed-franchise-portfolio-acquisition','title':'Distressed Franchise Portfolio Acquisition','verdict':'CONDITIONAL','bottom':'Attractive only as Avenue 1: partner with a real operator and buy cash-flowing units at distressed-but-not-broken prices. Avoid turnaround fantasies; this works when distress is seller/capital-structure driven, not brand/unit-economic rot.','market':'Acquire 2-10 existing franchise units from stressed owners, lenders, or undercapitalized franchisees. Customers are the end-market buyers of the acquired concept; Dan’s customer is effectively the franchisor/lender/seller needing a clean successor. Demand driver is franchisor pressure to keep units open and transfer weak operators; NE/NY/NJ/CT has dense franchise territory supply. Market size is an estimate because no clean public market exists; IFA says franchising spans 806k+ U.S. establishments and $893.9B output in 2024, creating a huge pool of resale candidates. Source: https://www.franchise.org/franchise-information/franchise-business-outlook',
'econ':[('Revenue per unit','$750K-$2.5M','Concept/FDD-specific; verify tax returns'),('SDE / EBITDA margin','8%-18% after normalized manager','Restaurant/service franchise resales often underwrite to SDE; source: https://www.bizbuysell.com/insight-report/'),('Average ticket / job','$8-$300+','Concept-specific'),('Customer frequency','Daily to annual','Concept-specific'),('Route density potential','High only for service franchises','Franchisor territory maps'),('Recurring revenue %','0%-70%','Depends on concept'),('SBA financeable?','Yes, if profitable and eligible',SBA)],
'cases':[('Bear','$1.5M','$150K','10%','$525K','3.5x','negative to 10%'),('Base','$3.0M','$360K','12%','$1.35M','3.75x','25%-45%'),('Bull','$5.0M','$750K','15%','$3.2M','4.25x','35%-60%')],
'franchises':'Targets are resale portfolios, not new franchises. Screen Neighborly, Authority Brands, Premium Service Brands, Ace Handyman, Mathnasium/Kumon, Dunkin/sub shops only if FDD Item 19 and store-level P&Ls are clean. Franchise fees often $40K-$75K and royalties commonly 5%-8%; verify current FDDs at https://www.franchimp.com/ and state FDD repositories.',
'competitors':'Strategic franchisees, multi-unit operators, franchisor workout teams, lenders/SBA special assets, private buyer groups, Unbridled Capital, FRANdata/Franchise Times deal intermediaries, and PE-backed platforms such as Neighborly/Authority Brands/Empower Brands. Fragmentation is high below 10 units. Moat is franchisor approval, operator bench, local density, and clean transfer execution.',
'sources':['https://www.franchise.org/franchise-information/franchise-business-outlook','https://www.bizbuysell.com/insight-report/','https://www.sba.gov/funding-programs/loans/7a-loans','https://www.franchimp.com/','https://www.franchisetimes.com/']
},
{
'slug':'candy-import-snacks-ecommerce-to-retail','title':'Candy / Import Snacks Ecommerce to Retail','verdict':'CONDITIONAL','bottom':'Avenue 2 consumer cash-on-cash play, not a durable moat by default. The only investable version is a proven local/import snack brand with high turns, impulse retail, and wholesale/event channels — pure ecommerce candy is too fad-driven.','market':'Specialty candy/import snacks sells international candy, freeze-dried candy, Asian snacks, novelty beverages and gift boxes through Shopify, TikTok, malls, tourist corridors and pop-ups. Customers skew Gen Z/families/gifting; B2C dominates with some wholesale/corporate gifting. Demand drivers are novelty, social media, gifting and affordable indulgence; NE/NYC tourist and college markets are relevant. Market size: U.S. confectionery retail sales exceeded $48B in 2023 per National Confectioners Association; specialty/import snack niche is an estimate. Source: https://candyusa.com/news/nca-releases-2024-state-of-treating-report/',
'econ':[('Revenue per unit','$500K-$1.5M','Specialty retail estimate; verify POS'),('SDE / EBITDA margin','8%-15%','Retail broker/SDE benchmarks; BizBuySell'),('Average ticket / job','$12-$35','Candy/snack retail estimate; Shopify/POS to verify'),('Customer frequency','2-8x/year','CRM/POS repeat purchase'),('Route density potential','Low; retail density better than routes','Store clustering'),('Recurring revenue %','5%-25%','Subscriptions/corporate gifts'),('SBA financeable?','Yes if profitable; inventory-heavy',SBA)],
'cases':[('Bear','$500K','$40K','8%','$120K','3.0x','low/negative'),('Base','$900K','$108K','12%','$378K','3.5x','20%-35%'),('Bull','$1.5M','$225K','15%','$1.0M','4.5x','35%-55%')],
'franchises':'Rocket Fizz, IT’SUGAR, Lolli & Pops, Kilwins, River Street Sweets, Sugar Factory-style concepts; typical franchise fees often $25K-$50K and royalties 5%-7% where franchised. Many import-snack winners are independent or licensed distributors; verify Item 19 before trusting AUV claims.',
'competitors':'IT’SUGAR, Lolli & Pops, Rocket Fizz, Economy Candy NYC, H Mart/Asian grocers, Five Below, Target, Amazon, TikTok Shop sellers, local mall candy stores. PE/strategic activity exists in confectionery brands but small retail remains fragmented. Moat is sourcing, social content, location, private label and event/wholesale relationships.',
'sources':['https://candyusa.com/news/nca-releases-2024-state-of-treating-report/','https://www.bizbuysell.com/insight-report/','https://www.sba.gov/funding-programs/loans/7a-loans','https://www.rocketfizz.com/franchise/','https://www.itsugar.com/']
},
{
'slug':'drive-thru-coffee-kiosk','title':'Drive-Thru Coffee Kiosk','verdict':'CONDITIONAL','bottom':'Potentially strong Avenue 2 if the site is exceptional and labor model is tight. New-build franchise risk is real: high capex, site selection dependency, and intense coffee competition make this a no-go without verified AUV/payback.','market':'Small-footprint drive-thru coffee sells beverages and snacks from kiosks/stands optimized for speed. Customers are commuters, parents, students and blue-collar/mobile workers; B2C dominates. Demand is habitual and high-frequency, but location is destiny. U.S. coffee shop market is large and growing; IBISWorld/Statista estimates vary, so use “multi-tens-of-billions estimate.” NE suburban commuter corridors and SFL drive-thru culture are relevant.','econ':[('Revenue per unit','$800K-$1.8M','Scooter’s/Biggby/Dutch Bros FDD summaries; verify current FDD'),('SDE / EBITDA margin','12%-22%','Manager-run beverage estimate'),('Average ticket / job','$6-$10','Coffee QSR estimate'),('Customer frequency','2-5x/week for regulars','Habitual beverage behavior'),('Route density potential','Site density, not routes','Drive-thru traffic counts'),('Recurring revenue %','High behavioral repeat; no contracts','POS loyalty data'),('SBA financeable?','Yes; new-build restaurant underwriting harder',SBA)],
'cases':[('Bear','$800K','$80K','10%','$280K','3.5x','negative'),('Base','$1.2M','$180K','15%','$675K','3.75x','20%-35%'),('Bull','$1.8M','$360K','20%','$1.62M','4.5x','35%-55%')],
'franchises':'Scooter’s Coffee, Biggby Coffee, Ellianos, Ziggi’s, 7 Brew, PJ’s Coffee, Dutch Bros (company/franchise mix historically). Public franchise portals cite initial investments often ~$500K-$1.5M+, franchise fees ~$30K-$50K, royalties around 5%-6% plus marketing. Verify current Item 7/19 via FDD.',
'competitors':'Dunkin, Starbucks, Dutch Bros, Scooter’s, 7 Brew, local coffee huts, convenience stores, McDonald’s. Consolidation exists around QSR franchisees but local markets are site-constrained. Moat is real estate, speed, morning habit, labor scheduling and brand consistency.',
'sources':['https://www.scooterscoffee.com/franchise','https://www.biggby.com/franchise/','https://www.entrepreneur.com/franchises/directory/scooters-coffee/335576','https://www.sba.gov/funding-programs/loans/7a-loans','https://www.dutchbros.com/']
},
{
'slug':'self-storage-portable-storage','title':'Self-Storage / Portable Storage','verdict':'GO','bottom':'One of the better Avenue 1 categories if Dan avoids ground-up self-storage development and focuses on portable storage/local moving containers with an operator. It has real recurring revenue, asset collateral, and route-density logic.','market':'Self-storage rents fixed units; portable storage rents delivered containers for moving, renovation, disaster recovery and business overflow. Customers split B2C movers/homeowners and B2B contractors, restorers, retailers and institutions. Demand is recurring/monthly and tied to life events, housing turnover and construction. U.S. self-storage has roughly 50k+ facilities and >1.7B rentable square feet per Self Storage Association; portable storage is a smaller niche estimate. Source: https://www.selfstorage.org/','econ':[('Revenue per unit','$600K-$2.0M local portable-storage depot','UNITS/PODS franchise estimates; verify FDD'),('SDE / EBITDA margin','18%-35%','Asset rental businesses; verify P&L'),('Average ticket / job','$150-$300/mo container rent + delivery','Portable storage pricing pages'),('Customer frequency','Monthly rental; 2-6 month duration common','Operator data'),('Route density potential','High within 30-mile depot radius','Dispatch economics'),('Recurring revenue %','60%-90% rental revenue','Monthly rental model'),('SBA financeable?','Yes; asset-heavy, collateral helps',SBA)],
'cases':[('Bear','$600K','$120K','20%','$420K','3.5x','15%-25%'),('Base','$1.2M','$300K','25%','$1.2M','4.0x','35%-55%'),('Bull','$2.0M','$700K','35%','$3.15M','4.5x','45%-70%')],
'franchises':'PODS, UNITS Moving and Portable Storage, Zippy Shell, 1-800-PACK-RAT territories/resales. UNITS franchise materials historically cite territory/depot model, franchise fee commonly around $55K and royalty/brand fees to verify. Self-storage franchises are less central; acquisition/development is more common.',
'competitors':'Public REITs Extra Space, Public Storage, CubeSmart, Life Storage (merged with Extra Space), National Storage Affiliates; portable competitors PODS, UNITS, Zippy Shell, 1-800-PACK-RAT, U-Haul U-Box and local trailer/container operators. PE/institutional capital is active in self-storage; portable local depots remain more fragmented.',
'sources':['https://www.selfstorage.org/','https://www.extraspace.com/self-storage/','https://www.pods.com/','https://unitsfranchisegroup.com/','https://www.sba.gov/funding-programs/loans/7a-loans']
},
{
'slug':'mens-health-hair-restoration-trt-clinic','title':"Men's Health / Hair Restoration / TRT Clinic",'verdict':'CONDITIONAL','bottom':'Commercially attractive but compliance-heavy. The investable version is an operator/physician partnership with conservative medical governance, not a bro-marketed TRT mill. Hair restoration can be high-ticket; TRT adds recurring revenue and regulatory risk.','market':'Clinics sell testosterone evaluation/therapy, ED care, weight/body composition, hair restoration/transplants, PRP and prescription hair-loss protocols. Customers are adult men; B2C cash-pay dominates with some insurance. Demand drivers: aging male population, telehealth normalization, GLP-1/body-composition adjacency, aesthetics destigmatization. Market size: Grand View Research estimates global men’s health market at $40B+ and hair restoration services market at multi-billion-dollar scale; U.S. clinic SAM is an estimate. Sources: https://www.grandviewresearch.com/industry-analysis/mens-health-market-report and https://www.grandviewresearch.com/industry-analysis/hair-restoration-services-market','econ':[('Revenue per unit','$750K-$2.5M','Clinic/franchise estimates; verify EMR/bank'),('SDE / EBITDA margin','12%-25% after clinician/medical director','Cash-pay clinic estimate'),('Average ticket / job','$150-$300/mo TRT; $4K-$15K hair restoration','Clinic price pages'),('Customer frequency','Monthly/quarterly TRT; one-time hair procedure','Protocol dependent'),('Route density potential','Multi-clinic hub/spoke possible','Local medspa model'),('Recurring revenue %','40%-75% if TRT/memberships dominate','EMR subscription cohorts'),('SBA financeable?','Possible, but MSO/CPOM/legal structure matters',SBA)],
'cases':[('Bear','$750K','$90K','12%','$315K','3.5x','low/negative'),('Base','$1.5M','$300K','20%','$1.2M','4.0x','30%-50%'),('Bull','$2.5M','$625K','25%','$2.8M','4.5x','40%-65%')],
'franchises':'Bosley, HairClub, Restore Hair, Gameday Men’s Health, Low T Center-style clinics, Limitless Male, QC Kinetix adjacent. Fees/royalties vary widely; Gameday franchise portals cite franchise fee often ~$49.5K and royalties/marketing to verify; medical FDDs and state CPOM rules are mandatory diligence.',
'competitors':'Bosley, HairClub, Hims & Hers, Ro, Gameday Men’s Health, Low T Center, local urology practices, medspas, dermatology/hair transplant surgeons. PE is active in medspa/derm/urology/MSO platforms. Moat is compliant medical oversight, patient acquisition CAC, retention, outcomes, physician relationships and brand trust.',
'sources':['https://www.grandviewresearch.com/industry-analysis/mens-health-market-report','https://www.grandviewresearch.com/industry-analysis/hair-restoration-services-market','https://www.fda.gov/drugs/postmarket-drug-safety-information-patients-and-providers/fda-drug-safety-communication-fda-cautions-about-using-testosterone-products-low-testosterone-due','https://www.gamedaymenshealth.com/franchise/','https://www.sba.gov/funding-programs/loans/7a-loans']
}]

def md_for(x):
    lines=[f"# {x['title']} — Deep Dive Investment Memo",'',f"## Verdict: {x['verdict']}",x['bottom'],'',"## 1. Category Definition & Demand Map",x['market'],'',"## 2. Economics to Underwrite",'| Metric | Typical Range | Source |','|--------|--------------|--------|']
    for r in x['econ']: lines.append(f"| {r[0]} | {r[1]} | {r[2]} |")
    lines += ['',"## 3. Unit Economics Model (Three-Case)",'','| Case | Revenue | SDE | SDE Margin | Entry Price | Multiple | Cash-on-Cash Year 1 |','|------|---------|-----|-----------|-------------|----------|---------------------|']
    for c in x['cases']: lines.append('| '+' | '.join(c)+' |')
    lines += ['',"**Key assumptions:**",'- Entry multiples: 3-4.5x SDE at Dan\'s scale ($200-500K SDE). NOT 8-10x.','- SBA 7(a): 10-year term, ~11% rate (2026), 10% down','- Cash-on-cash = (SDE - debt service) / down payment','- Operator partner: Dan can hire/partner with an operator — do not penalize lack of direct experience','',"## 4. Path-Specific Buybox",'What makes a GOOD acquisition target in this category?','- Revenue range: '+x['cases'][1][1]+' base target; avoid subscale unless cheap.','- SDE range: $200K-$500K+ preferred; normalize for paid manager/operator.','- Years in business: 3+ years with tax returns, POS/CRM, lease/territory control.','- Route density / customer count: dense local territory; recurring or repeat customers documented.','- Key assets to verify: tax returns, bank deposits, customer cohorts, leases/territories, equipment, licenses, staff retention.','- Red flags to avoid: seller-as-business, unverifiable add-backs, declining traffic, capex cliff, regulatory ambiguity, franchisor transfer issues.','', 'What makes a good FRANCHISE candidate?',x['franchises'],'',"## 5. Competitive Landscape",x['competitors'],'',"## 6. Financing, Valuation & Capital Discipline",'- Typical deal structure: asset purchase where possible, seller note/earnout for transition risk, working-capital peg, non-compete and training agreement.','- SBA eligibility and typical loan terms: '+SBA,'- Down payment required at Dan\'s scale: roughly 10%-20% equity plus diligence/legal and working capital reserve.','- Payback period at base case: usually 2.5-5 years if bought at 3.5-4.0x verified SDE and manager cost is real.','- Honest multiple arbitrage: underwrite ~3x in → 4x out at this scale; do not assume institutional roll-up multiples.','',"## 7. 90-Day Roadmap (If Dan Pursues This)",'- Phase 1 (Days 1-30): Market mapping in Boston/NE first; scrape brokers/franchise resale listings; request FDDs where applicable; build source-of-truth comp table.','- Phase 2 (Days 31-60): Identify operator partner profile; review 5-10 actual P&Ls; site visits/customer mystery shops; build 3-case model.','- Phase 3 (Days 61-90): Pick LOI target or franchise signing decision; negotiate seller note/training; run legal/regulatory review before exclusivity.','',"## 8. Kill Criteria",'- No clean tax-return support for SDE or revenue.','- Paid-manager model fails debt service.','- Customer demand is fad-driven with weak repeat behavior.','- Transfer requires franchisor/landlord consent on unattractive terms.','- Required capex exceeds modeled reserve or creates >5-year payback.','- Legal/compliance structure is unclear or dependent on aggressive interpretation.','',"## Sources"]
    lines += [f'- {s}' for s in x['sources']]
    return '\n'.join(lines)+'\n'

def body_html(x, md):
    # basic markdown to HTML, preserve tables as simple pre? generate sections manually instead
    out=f'''<section class="hero">\n<div class="kicker">Deep Dive · Investment Memo</div>\n<h1>{html.escape(x['title'])} — Deep Dive Investment Memo</h1>\n<p class="lede">{html.escape(x['bottom'])}</p>\n<div class="meta"><span class="tag tag-gold">{x['verdict']}</span><span class="tag tag-blue">Dan Business Path</span><span class="tag tag-gold">Confidence: Medium</span></div>\n</section>\n<div class="verdict-box"><h2>Verdict: {x['verdict']}</h2><p class="one-line">{html.escape(x['bottom'])}</p></div>\n'''
    sections=md.split('\n## ')[1:]
    for sec in sections[1:]:
        title,_,content=sec.partition('\n')
        out+=f'<h2>{html.escape(title)}</h2>\n'
        if '| Metric |' in content or '| Case |' in content:
            out+='<pre class="card" style="white-space:pre-wrap">'+html.escape(content)+'</pre>\n'
        else:
            paras=[]
            for block in content.strip().split('\n\n'):
                if block.startswith('- '): paras.append('<ul>'+''.join('<li>'+html.escape(i[2:])+'</li>' for i in block.split('\n') if i.startswith('- '))+'</ul>')
                else: paras.append('<p>'+html.escape(block).replace('\n','<br>')+'</p>')
            out+='\n'.join(paras)+'\n'
    return out

for x in items:
    md=md_for(x)
    (BASE/'deep-dives'/f"{x['slug']}.md").write_text(md)
    (OBS/f"{x['slug']}.md").write_text(md)
    html_doc=start+body_html(x,md)+end
    (BASE/f"{x['slug']}.html").write_text(html_doc)
print('wrote', len(items), 'deep dives')
